[
  {
    "number": 25288,
    "title": "How to skip to validate selected output tensors in python unit tests?",
    "created_at": "2020-06-30T15:20:42Z",
    "closed_at": "2020-07-01T14:44:00Z",
    "labels": [
      "question",
      "Intel"
    ],
    "url": "https://github.com/PaddlePaddle/Paddle/issues/25288",
    "body": "Hi,\r\n\r\nThere are operators like LRN which are having one of an outputs (MidOut) that is no use for user , but it contains intermediate data\r\nthat are speeding computation of LRN grad operator. In unit tests, (test_check_output) this MidOut is also verified if it contains valid / expected data. Problem is that what is inside MidOut is implementation specific. oneDNN LRN will produce MidOut with diffrent kind of data, because LRN oneDNN grad op is diffrent in implementation to Paddle CPU LRN grad. So unit test may fail\r\ndue to diffrent kind of data being put into MidOut. So my question is : is it possible to skip comparing MidOut tensor in Unit tests of LRN oneDNN ? If positive then how can I do that? ",
    "comments_url": "https://api.github.com/repos/PaddlePaddle/Paddle/issues/25288/comments",
    "author": "jczaja",
    "comments": [
      {
        "user": "zhiqiu",
        "created_at": "2020-07-01T05:46:28Z",
        "body": "Hi, you can call `self.check_output(no_check_set=['MidOut'])` , so `MidOut` will not be checked."
      },
      {
        "user": "jczaja",
        "created_at": "2020-07-01T14:44:00Z",
        "body": "@zhiqiu  Thanks for suggestion! To actually have it working I also needed to add *lrn* to *no_check_set_whitelist*."
      }
    ]
  },
  {
    "number": 23021,
    "title": "\u52a8\u6001\u56fe\u4f7f\u7528fluid.dygraph.Layer.create_parameter\u62a5\u544a\u7f3a\u5c11\u53c2\u6570\u9519\u8bef",
    "created_at": "2020-03-16T02:27:37Z",
    "closed_at": "2020-03-16T03:46:01Z",
    "labels": [
      "question",
      "dygraph"
    ],
    "url": "https://github.com/PaddlePaddle/Paddle/issues/23021",
    "body": "\u00a01\uff09PaddlePaddle\u7248\u672c\uff1a1.7.0\r\n\u52a8\u6001\u56fe\u4f7f\u7528create_parameter\u51fa\u73b0\u7f3a\u5c11\u53c2\u6570self\u9519\u8bef,\u53ef\u662f\u5b98\u65b9\u6587\u6863\u91cc\u5e76\u6ca1\u6709\u8fd9\u4e2a\u53c2\u6570\u3002\r\n\u4e0b\u9762\u662f\u4e00\u4e2a\u7b80\u5355\u7684\u793a\u4f8b\uff0c\u5982\u679c\u662f\u6211\u4f7f\u7528\u6709\u95ee\u9898\u8fd8\u5e0c\u671b\u80fd\u591f\u7ed9\u4e00\u4e2a\u4f8b\u5b50\uff0c\u5982\u4f55\u4f7f\u7528\u3002\r\nimport paddle.fluid as fluid\r\nwith fluid.dygraph.guard():\r\n   w=fluid.dygraph.Layer.create_parameter(dtype='float64',shape=[2,2])\r\n\u62a5\u9519\uff1a\r\nTraceback (most recent call last):\r\n  File \"14.py\", line 3, in <module>\r\n    w=fluid.dygraph.Layer.create_parameter(dtype='float64',shape=[2,2])\r\nTypeError: create_parameter() missing 1 required positional argument: 'self'\r\n",
    "comments_url": "https://api.github.com/repos/PaddlePaddle/Paddle/issues/23021/comments",
    "author": "zhangylch",
    "comments": [
      {
        "user": "qingqing01",
        "created_at": "2020-03-16T03:42:22Z",
        "body": "@zylustc \r\n\r\n\u6b64\u51fd\u6570\u9700\u8981\u5728\u7ee7\u627f fluid.Layer\u7684sub-class\u4e2d\u7528\uff0c\u800c\u4e0d\u662f\u5f53\u505a\u666e\u901a\u7684function\u8c03\u7528\u3002\u6b63\u786e\u7684\u7528\u6cd5\u662f:\r\n\r\n```\r\n\r\nclass MyModel(fluid.Layer):\r\n    def __init__(self):\r\n        super(MyModel, self).__init__()\r\n        self.w = self.create_parameter(\r\n            dtype='float64',\r\n            shape=[2, 2])\r\n\r\nwith fluid.dygraph.guard():\r\n    model = MyModel()\r\n    print(model.w)\r\n```"
      }
    ]
  },
  {
    "number": 418,
    "title": "\"Double requirement given\" problem",
    "created_at": "2016-11-10T03:34:13Z",
    "closed_at": "2016-11-11T03:20:08Z",
    "labels": [
      "question"
    ],
    "url": "https://github.com/PaddlePaddle/Paddle/issues/418",
    "body": "I got below errors. Currently, I resolved this problem by remove one of them. I am working with the latest code. So I guess the problem is due to my docker image is outdated. But I don't want to download the latest docker image and have a try. Could you tell me how to solve this problem?\r\n```\r\nFirst time run paddle, need to install some python dependencies.\r\nUnpacking /usr/local/opt/paddle/share/wheels/paddle-0.8.0b-py2-none-any.whl\r\nUnpacking /usr/local/opt/paddle/share/wheels/paddle-0.8.0b1-py2-none-any.whl\r\nCleaning up...\r\nDouble requirement given: paddle==0.8.0b1 from file:///usr/local/opt/paddle/share/wheels/paddle-0.8.0b1-py2-none-any.whl (already in paddle==0.8.0b from file:///usr/local/opt/paddle/share/wheels/paddle-0.8.0b-py2-none-any.whl, name='paddle')\r\nStoring debug log for failure in /root/.pip/pip.log\r\npip install wheels failed. \r\nPlease use 'sudo paddle' at the first time you use PaddlePaddle\r\nPaddlePaddle will install some python dependencies automatically.\r\n```\r\n\r\n```\r\n\r\nFirst time run paddle, need to install some python dependencies.\r\nUnpacking /usr/local/opt/paddle/share/wheels/paddle-0.8.0b2-py2-none-any.whl\r\nUnpacking /usr/local/opt/paddle/share/wheels/py_paddle-0.8.0b-cp27-none-linux_x86_64.whl\r\nUnpacking /usr/local/opt/paddle/share/wheels/py_paddle-0.8.0b1-cp27-none-linux_x86_64.whl\r\nCleaning up...\r\nDouble requirement given: py-paddle==0.8.0b1 from file:///usr/local/opt/paddle/share/wheels/py_paddle-0.8.0b1-cp27-none-linux_x86_64.whl (already in py-paddle==0.8.0b from file:///usr/local/opt/paddle/share/wheels/py_paddle-0.8.0b-cp27-none-linux_x86_64.whl, name='py-paddle')\r\nStoring debug log for failure in /root/.pip/pip.log\r\npip install wheels failed. \r\nPlease use 'sudo paddle' at the first time you use PaddlePaddle\r\nPaddlePaddle will install some python dependencies automatically\r\n```\r\n",
    "comments_url": "https://api.github.com/repos/PaddlePaddle/Paddle/issues/418/comments",
    "author": "zuowang",
    "comments": [
      {
        "user": "luotao1",
        "created_at": "2016-11-10T03:44:32Z",
        "body": "\u2018 I am working with the latest code\u2019\uff1a\u8bf7\u95ee\u4f60\u662f\u7528\u6e90\u7801\u7f16\u8bd1develop\u5206\u652f\u51fa\u73b0\u4e0a\u8ff0\u95ee\u9898\u7684\u4e48\n"
      },
      {
        "user": "zuowang",
        "created_at": "2016-11-10T03:54:19Z",
        "body": "When I ran command `paddle version`.\n"
      },
      {
        "user": "reyoung",
        "created_at": "2016-11-10T04:06:46Z",
        "body": "@zuowang \nPlease uninstall Paddle before install a new version.\n\n``` bash\npip uninstall -u paddle py_paddle\nrm -rf /usr/local/bin/paddle /usr/local/opt/paddle\n```\n"
      },
      {
        "user": "reyoung",
        "created_at": "2016-11-10T04:59:56Z",
        "body": "@zuowang \nAnd clean your git checkout directory by\n\n``` bash\ngit clean -fxd  # note it is danger, please commit your local change before\n```\n"
      },
      {
        "user": "qingqing01",
        "created_at": "2016-11-10T12:20:18Z",
        "body": "@zuowang Maybe you need to remove the package in `Paddle/paddle/dist/` path by  `rm -rf Paddle/paddle/dist/*`. Then make install again.\n"
      }
    ]
  },
  {
    "number": 159,
    "title": "libprotobuf ERROR while running sentiment demo",
    "created_at": "2016-10-04T23:22:09Z",
    "closed_at": "2016-10-06T04:29:57Z",
    "labels": [
      "question"
    ],
    "url": "https://github.com/PaddlePaddle/Paddle/issues/159",
    "body": "1. paddle version\n   git version: commit 29c16e22420b8b69d17572accd2f6fc0239c8c7e\n   paddle compiled from source, with the options: cmake .. -DWITH_GPU=ON -DWITH_DOC=ON -DWITH_SWIG_PY=ON -DCMAKE_INSTALL_PREFIX=/data/user/program/pddl_build/\n   make and make install success.\n2. protoc --version\n   libprotoc 2.5.0\n3. run the sentiment demo:\n   cd /demo/sentiment/data/\n   ./get_imdb.sh\n   cd ..\n   ./preprocess.sh\n   the above steps are good.\n   However, run ./train.sh, I get the following error msg:\n# \n\nI1004 16:22:13.414708 12100 Util.cpp:144] commandline: /usr/local/bin/../opt/paddle/bin/paddle_trainer --config=trainer_config.py --save_dir=./model_output --job=train --use_gpu=false --trainer_count=4 --num_passes=10 --log_period=10 --dot_period=20 --show_parameter_stats_period=100 --test_all_data_in_one_period=1 \nI1004 16:22:13.414949 12100 Util.cpp:113] Calling runInitFunctions\nI1004 16:22:13.415261 12100 Util.cpp:126] Call runInitFunctions done.\n[INFO 2016-10-04 16:22:13,802 networks.py:1125] The input order is [word, label]\n[INFO 2016-10-04 16:22:13,802 networks.py:1132] The output order is [**cost_0**]\n[libprotobuf ERROR google/protobuf/message_lite.cc:123] Can't parse message of type \"paddle.TrainerConfig\" because it is missing required fields: model_config.parameters[0].learning_rate, model_config.parameters[0].momentum, model_config.parameters[1].learning_rate, model_config.parameters[1].momentum, model_config.parameters[2].learning_rate, model_config.parameters[2].momentum, model_config.parameters[3].learning_rate, model_config.parameters[3].momentum, model_config.parameters[4].learning_rate, model_config.parameters[4].momentum, model_config.parameters[5].momentum, model_config.parameters[6].momentum, model_config.parameters[7].learning_rate, model_config.parameters[7].momentum, model_config.parameters[8].learning_rate, model_config.parameters[8].momentum, model_config.parameters[9].learning_rate, model_config.parameters[9].momentum, model_config.parameters[10].momentum, model_config.parameters[11].momentum, model_config.parameters[12].learning_rate, model_config.parameters[12].momentum, model_config.parameters[13].learning_rate, model_config.parameters[13].momentum, model_config.parameters[14].learning_rate, model_config.parameters[14].momentum, model_config.parameters[15].momentum, model_config.parameters[16].momentum, model_config.parameters[17].learning_rate, model_config.parameters[17].momentum\nF1004 16:22:13.825393 12100 TrainerConfigHelper.cpp:59] Check failed: m->conf.ParseFromString(configProtoStr) \n**\\* Check failure stack trace: ***\n    @     0x7fc3d0879daa  (unknown)\n    @     0x7fc3d0879ce4  (unknown)\n    @     0x7fc3d08796e6  (unknown)\n    @     0x7fc3d087c687  (unknown)\n    @           0x6aa559  paddle::TrainerConfigHelper::TrainerConfigHelper()\n    @           0x6aa924  paddle::TrainerConfigHelper::createFromFlags()\n    @           0x53af53  main\n    @     0x7fc3cfa85ec5  (unknown)\n    @           0x546695  (unknown)\n    @              (nil)  (unknown)\n# /usr/local/bin/paddle: line 46: 12100 Aborted                 (core dumped) ${DEBUGGER} $MYDIR/../opt/paddle/bin/paddle_trainer ${@:2}\n\nCould you please help to check what is this about?\n",
    "comments_url": "https://api.github.com/repos/PaddlePaddle/Paddle/issues/159/comments",
    "author": "cactiball",
    "comments": [
      {
        "user": "emailweixu",
        "created_at": "2016-10-05T03:49:54Z",
        "body": "It looks like your conflict version of paddle c++ binary and python interface. Your install prefix is different from the path shown in the above log\n"
      }
    ]
  },
  {
    "number": 152,
    "title": "questions about sparse multiplication",
    "created_at": "2016-09-30T09:56:02Z",
    "closed_at": "2016-10-09T02:15:53Z",
    "labels": [
      "question"
    ],
    "url": "https://github.com/PaddlePaddle/Paddle/issues/152",
    "body": "I verified  sparse multiplication according to your codes.  I designed my demo  which is as follows:\n# include<iostream>\n# include<stdlib.h>\n\nusing namespace std;\nint main()\n{\n    void colVecAddTo(int\\* a, int\\* b, int c, int len, int aWidth, int bWidth);\n    int a[3] = {1, 1, 1};\n\n```\n                                                    //b=[0, 1, 0, 2, 0; 1, 0, 0, 0, 0; 0, 0, 0, 2, 5]  SPARSE_CSR\nint b_value[5] = {1, 2, 1, 2, 5};\nint b_col[5] = {1, 3, 0, 3, 4};\nint b_row[4] = {0, 2, 3, 5};\nint f[5] = {0, 0, 0, 0, 0};\n\nint *A = a;\nint *B = b_value;\nint *C = f;\n\nint *rows = b_row;\nint *cols = b_col;\n\nint m = 3;                    //a->getWidth()   \nint width_ = 5;               //b->getWidth()\nint height_ = 1;              //a->getHeight()\n\nfor (int j = 0 ;j < 3; ++j )   //3 is b->getHeight()\n{\n    int start = b_row[j];             //start = b->getRowStartIdx(j)\n    int end = b_row[j + 1];           //end = b->getRowStartIdx(j + 1)\n    for (int i = start; i < end; ++i)\n    {\n        colVecAddTo(C + cols[i], A + j, B[i], height_, width_, 3);\n        //cout<<*(C + cols[i])<<endl;\n    }\n}\n\nsystem(\"pause\");\nreturn 0;\n```\n\n}\n\n void colVecAddTo(int\\* aa, int\\* bb, int cc, int len, int aWidth, int bWidth) \n{\n      for ( int ii = 0; ii < len; ++ii)\n     {\n         aa[ii \\* aWidth] += bb[ii \\* bWidth] \\* cc;\n     cout<<aa[ii \\* aWidth]<<endl;\n     }\n}\nThe correct result should be 1 1 0 4 5,   but the rusult of my demo is  1 2 1 4 5  . Could you help me ?\n\nWhat's more , could you show me more details or reference materials about sparse multiplication? Thank you very much.\n",
    "comments_url": "https://api.github.com/repos/PaddlePaddle/Paddle/issues/152/comments",
    "author": "shenhuinuist",
    "comments": [
      {
        "user": "hedaoyuan",
        "created_at": "2016-10-01T14:31:47Z",
        "body": "What you print is not the value of C[i](i = 0/1/2/3/4), but the value of C + cols[i](cols[i] = .......).\nPrint outside the loop, and the result is 1 1 0 4 5.\n"
      }
    ]
  },
  {
    "number": 94,
    "title": "Install whl failed",
    "created_at": "2016-09-19T15:22:45Z",
    "closed_at": "2016-09-21T12:44:05Z",
    "labels": [
      "question"
    ],
    "url": "https://github.com/PaddlePaddle/Paddle/issues/94",
    "body": "I can successfully build out the paddle but while I install \"py_paddle-0.8.0b0-cp27-cp27mu-linux_x86_64.whl\", it failed and promt:\n~/workspace/Paddle/build$ sudo pip install /opt/paddle/share/wheels/*.whl\npy_paddle-0.8.0b0-cp27-cp27mu-linux_x86_64.whl is not a supported wheel on this platform.\nStoring debug log for failure in /home/yu/.pip/pip.log\n\nHow shall I fix it or work around it?\n\nMy configuration:\ncmake -DWITH_GPU=ON -DWITH_DOC=OFF -DMKL_ROOT=/opt/intel/compilers_and_libraries_2016.3.210/linux/mkl/ -DCUDNN_ROOT=/usr/local/cuda -DWITH_SWIG_PY=ON -DCMAKE_INSTALL_PREFIX=/ ..\n\npaddle version\nPaddlePaddle 0.8.0b0, compiled with\n    with_avx: ON\n    with_gpu: ON\n    with_double: OFF\n    with_python: ON\n    with_rdma: OFF\n    with_glog: ON\n    with_gflags: ON\n    with_metric_learning: \n    with_timer: OFF\n    with_predict_sdk: \n",
    "comments_url": "https://api.github.com/repos/PaddlePaddle/Paddle/issues/94/comments",
    "author": "apollos",
    "comments": [
      {
        "user": "F0REacH",
        "created_at": "2016-09-19T15:30:03Z",
        "body": "Hi, @apollos . I've had similar issue: python/pip was installed with multiple versions 2.7 and 3.5\n\n```\nforeach@linux-PC:~> pip2.7 --version\npip 8.1.2 from /usr/lib/python2.7/site-packages (python 2.7)\nforeach@linux-PC:~> pip --version\npip 8.1.1 from /usr/lib/python3.5/site-packages (python 3.5)\n```\n\nHad to run \n\n> foreach@linux-PC:~> sudo update-alternatives --config pip \n> to set pip version to 2.7 manually\n"
      },
      {
        "user": "apollos",
        "created_at": "2016-09-20T10:56:56Z",
        "body": "Thanks for your help. But it seems not my issue\n\n:~$ pip --version\npip 1.5.4 from /usr/lib/python2.7/dist-packages (python 2.7)\n\nMy pip is from python2.7.\n\nAnd I do try pip2 but same issue\n\nsudo pip2 install py_paddle-0.8.0b0-cp27-cp27mu-linux_x86_64.whl \npy_paddle-0.8.0b0-cp27-cp27mu-linux_x86_64.whl is not a supported wheel on this platform.\nStoring debug log for failure in /home/yu/.pip/pip.log\n\n 1 ------------------------------------------------------------\n  2 /usr/bin/pip2 run on Tue Sep 20 18:54:32 2016\n  3 py_paddle-0.8.0b0-cp27-cp27mu-linux_x86_64.whl is not a supported wheel on this platform.\n  4 Exception information:\n  5 Traceback (most recent call last):\n  6   File \"/usr/lib/python2.7/dist-packages/pip/basecommand.py\", line 122, in main\n  7     status = self.run(options, args)\n  8   File \"/usr/lib/python2.7/dist-packages/pip/commands/install.py\", line 257, in run\n  9     InstallRequirement.from_line(name, None))\n 10   File \"/usr/lib/python2.7/dist-packages/pip/req.py\", line 168, in from_line\n 11     raise UnsupportedWheel(\"%s is not a supported wheel on this platform.\" % wheel.filename)\n 12 UnsupportedWheel: py_paddle-0.8.0b0-cp27-cp27mu-linux_x86_64.whl is not a supported wheel on this platform.\n"
      },
      {
        "user": "reyoung",
        "created_at": "2016-09-21T02:07:30Z",
        "body": "This because the pip version is too old, but wheel package is latest.\n\nPlease update your pip by `pip install pip --upgrade`\n"
      }
    ]
  }
]