[
  {
    "number": 418,
    "title": "\"Double requirement given\" problem",
    "created_at": "2016-11-10T03:34:13Z",
    "closed_at": "2016-11-11T03:20:08Z",
    "labels": [
      "question"
    ],
    "url": "https://github.com/PaddlePaddle/Paddle/issues/418",
    "body": "I got below errors. Currently, I resolved this problem by remove one of them. I am working with the latest code. So I guess the problem is due to my docker image is outdated. But I don't want to download the latest docker image and have a try. Could you tell me how to solve this problem?\r\n```\r\nFirst time run paddle, need to install some python dependencies.\r\nUnpacking /usr/local/opt/paddle/share/wheels/paddle-0.8.0b-py2-none-any.whl\r\nUnpacking /usr/local/opt/paddle/share/wheels/paddle-0.8.0b1-py2-none-any.whl\r\nCleaning up...\r\nDouble requirement given: paddle==0.8.0b1 from file:///usr/local/opt/paddle/share/wheels/paddle-0.8.0b1-py2-none-any.whl (already in paddle==0.8.0b from file:///usr/local/opt/paddle/share/wheels/paddle-0.8.0b-py2-none-any.whl, name='paddle')\r\nStoring debug log for failure in /root/.pip/pip.log\r\npip install wheels failed. \r\nPlease use 'sudo paddle' at the first time you use PaddlePaddle\r\nPaddlePaddle will install some python dependencies automatically.\r\n```\r\n\r\n```\r\n\r\nFirst time run paddle, need to install some python dependencies.\r\nUnpacking /usr/local/opt/paddle/share/wheels/paddle-0.8.0b2-py2-none-any.whl\r\nUnpacking /usr/local/opt/paddle/share/wheels/py_paddle-0.8.0b-cp27-none-linux_x86_64.whl\r\nUnpacking /usr/local/opt/paddle/share/wheels/py_paddle-0.8.0b1-cp27-none-linux_x86_64.whl\r\nCleaning up...\r\nDouble requirement given: py-paddle==0.8.0b1 from file:///usr/local/opt/paddle/share/wheels/py_paddle-0.8.0b1-cp27-none-linux_x86_64.whl (already in py-paddle==0.8.0b from file:///usr/local/opt/paddle/share/wheels/py_paddle-0.8.0b-cp27-none-linux_x86_64.whl, name='py-paddle')\r\nStoring debug log for failure in /root/.pip/pip.log\r\npip install wheels failed. \r\nPlease use 'sudo paddle' at the first time you use PaddlePaddle\r\nPaddlePaddle will install some python dependencies automatically\r\n```\r\n",
    "comments_url": "https://api.github.com/repos/PaddlePaddle/Paddle/issues/418/comments",
    "author": "zuowang",
    "comments": [
      {
        "user": "luotao1",
        "created_at": "2016-11-10T03:44:32Z",
        "body": "\u2018 I am working with the latest code\u2019\uff1a\u8bf7\u95ee\u4f60\u662f\u7528\u6e90\u7801\u7f16\u8bd1develop\u5206\u652f\u51fa\u73b0\u4e0a\u8ff0\u95ee\u9898\u7684\u4e48\n"
      },
      {
        "user": "zuowang",
        "created_at": "2016-11-10T03:54:19Z",
        "body": "When I ran command `paddle version`.\n"
      },
      {
        "user": "reyoung",
        "created_at": "2016-11-10T04:06:46Z",
        "body": "@zuowang \nPlease uninstall Paddle before install a new version.\n\n``` bash\npip uninstall -u paddle py_paddle\nrm -rf /usr/local/bin/paddle /usr/local/opt/paddle\n```\n"
      },
      {
        "user": "reyoung",
        "created_at": "2016-11-10T04:59:56Z",
        "body": "@zuowang \nAnd clean your git checkout directory by\n\n``` bash\ngit clean -fxd  # note it is danger, please commit your local change before\n```\n"
      },
      {
        "user": "qingqing01",
        "created_at": "2016-11-10T12:20:18Z",
        "body": "@zuowang Maybe you need to remove the package in `Paddle/paddle/dist/` path by  `rm -rf Paddle/paddle/dist/*`. Then make install again.\n"
      }
    ]
  },
  {
    "number": 159,
    "title": "libprotobuf ERROR while running sentiment demo",
    "created_at": "2016-10-04T23:22:09Z",
    "closed_at": "2016-10-06T04:29:57Z",
    "labels": [
      "question"
    ],
    "url": "https://github.com/PaddlePaddle/Paddle/issues/159",
    "body": "1. paddle version\n   git version: commit 29c16e22420b8b69d17572accd2f6fc0239c8c7e\n   paddle compiled from source, with the options: cmake .. -DWITH_GPU=ON -DWITH_DOC=ON -DWITH_SWIG_PY=ON -DCMAKE_INSTALL_PREFIX=/data/user/program/pddl_build/\n   make and make install success.\n2. protoc --version\n   libprotoc 2.5.0\n3. run the sentiment demo:\n   cd /demo/sentiment/data/\n   ./get_imdb.sh\n   cd ..\n   ./preprocess.sh\n   the above steps are good.\n   However, run ./train.sh, I get the following error msg:\n# \n\nI1004 16:22:13.414708 12100 Util.cpp:144] commandline: /usr/local/bin/../opt/paddle/bin/paddle_trainer --config=trainer_config.py --save_dir=./model_output --job=train --use_gpu=false --trainer_count=4 --num_passes=10 --log_period=10 --dot_period=20 --show_parameter_stats_period=100 --test_all_data_in_one_period=1 \nI1004 16:22:13.414949 12100 Util.cpp:113] Calling runInitFunctions\nI1004 16:22:13.415261 12100 Util.cpp:126] Call runInitFunctions done.\n[INFO 2016-10-04 16:22:13,802 networks.py:1125] The input order is [word, label]\n[INFO 2016-10-04 16:22:13,802 networks.py:1132] The output order is [**cost_0**]\n[libprotobuf ERROR google/protobuf/message_lite.cc:123] Can't parse message of type \"paddle.TrainerConfig\" because it is missing required fields: model_config.parameters[0].learning_rate, model_config.parameters[0].momentum, model_config.parameters[1].learning_rate, model_config.parameters[1].momentum, model_config.parameters[2].learning_rate, model_config.parameters[2].momentum, model_config.parameters[3].learning_rate, model_config.parameters[3].momentum, model_config.parameters[4].learning_rate, model_config.parameters[4].momentum, model_config.parameters[5].momentum, model_config.parameters[6].momentum, model_config.parameters[7].learning_rate, model_config.parameters[7].momentum, model_config.parameters[8].learning_rate, model_config.parameters[8].momentum, model_config.parameters[9].learning_rate, model_config.parameters[9].momentum, model_config.parameters[10].momentum, model_config.parameters[11].momentum, model_config.parameters[12].learning_rate, model_config.parameters[12].momentum, model_config.parameters[13].learning_rate, model_config.parameters[13].momentum, model_config.parameters[14].learning_rate, model_config.parameters[14].momentum, model_config.parameters[15].momentum, model_config.parameters[16].momentum, model_config.parameters[17].learning_rate, model_config.parameters[17].momentum\nF1004 16:22:13.825393 12100 TrainerConfigHelper.cpp:59] Check failed: m->conf.ParseFromString(configProtoStr) \n**\\* Check failure stack trace: ***\n    @     0x7fc3d0879daa  (unknown)\n    @     0x7fc3d0879ce4  (unknown)\n    @     0x7fc3d08796e6  (unknown)\n    @     0x7fc3d087c687  (unknown)\n    @           0x6aa559  paddle::TrainerConfigHelper::TrainerConfigHelper()\n    @           0x6aa924  paddle::TrainerConfigHelper::createFromFlags()\n    @           0x53af53  main\n    @     0x7fc3cfa85ec5  (unknown)\n    @           0x546695  (unknown)\n    @              (nil)  (unknown)\n# /usr/local/bin/paddle: line 46: 12100 Aborted                 (core dumped) ${DEBUGGER} $MYDIR/../opt/paddle/bin/paddle_trainer ${@:2}\n\nCould you please help to check what is this about?\n",
    "comments_url": "https://api.github.com/repos/PaddlePaddle/Paddle/issues/159/comments",
    "author": "cactiball",
    "comments": [
      {
        "user": "emailweixu",
        "created_at": "2016-10-05T03:49:54Z",
        "body": "It looks like your conflict version of paddle c++ binary and python interface. Your install prefix is different from the path shown in the above log\n"
      }
    ]
  }
]