[
  {
    "number": 455,
    "title": "Bug: Example on poems crashes with `ValueError: Model is None and does not exist in passed completion_response`",
    "created_at": "2025-02-06T17:13:16Z",
    "closed_at": "2025-02-06T17:49:54Z",
    "labels": [],
    "url": "https://github.com/bespokelabsai/curator/issues/455",
    "body": "Steps to reproduce:\n\n1. Run the example provided in the README that produces poems. Code:\n\n```python\nfrom typing import List\nfrom dotenv import load_dotenv\nfrom pydantic import BaseModel, Field\nfrom bespokelabs import curator\n\nload_dotenv()\n\nclass Poem(BaseModel):\n    poem: str = Field(description=\"A poem.\")\n\n\nclass Poems(BaseModel):\n    poems_list: List[Poem] = Field(description=\"A list of poems.\")\n\n\nllm = curator.LLM(model_name=\"gpt-4o-mini\", response_format=Poems)\npoems = llm([\"Write two poems about the importance of data in AI.\", \n              \"Write three haikus about the importance of data in AI.\"])\nprint(poems.to_pandas())\n```\n\n2. Run the code\n3. The script will crash with these errors (obviously, the produced texts may change for you):\n```\nERROR - Request 1 failed permanently after exhausting all 10 retry attempts. Errors: ['Model is None and does not exist in passed completion_response. Passed completion_response={\\'id\\': \\'chatcmpl-AxzhI7MCWs66BlfHCYkA7BmMYaCoB\\', \\'object\\': \\'chat.completion\\', \\'created\\': 1738861880, \\'model\\': \\'gpt-4o-mini-2024-07-18\\', \\'choices\\': [{\\'index\\': 0, \\'message\\': {\\'role\\': \\'assistant\\', \\'content\\': \\'{\"poems_list\":[{\"poem\":\"Patterns hidden deep,\\\\\\\\nData whispers in the dark,\\\\\\\\nTruths brought into light.\"},{\"poem\":\"Bytes of knowledge flow,\\\\\\\\nLearning from what once was learned,\\\\\\\\nAI grows and knows.\"},{\"poem\":\"Numbers tell a tale,\\\\\\\\nLogic framed in lines of code,\\\\\\\\nData, heart of thought.\"}]}\\', \\'refusal\\': None}, \\'logprobs\\': None, \\'finish_reason\\': \\'stop\\'}] ....\n```\n\nI am using a normal OpenAI key, and it is a fresh installation of curator.\n```\nbespokelabs-curator==0.1.18.post1\n```\n\nThanks!",
    "comments_url": "https://api.github.com/repos/bespokelabsai/curator/issues/455/comments",
    "author": "AlexMV12",
    "comments": [
      {
        "user": "kartik4949",
        "created_at": "2025-02-06T17:18:51Z",
        "body": "@AlexMV12 Hello,\nare you using python3.13?\nalso could you try to degrade litellm version to 1.55.8?\nLitellm latest release have some broken apis.\nwe will release  a patch soon\nThanks"
      },
      {
        "user": "shreyaspimpalgaonkar",
        "created_at": "2025-02-06T17:49:54Z",
        "body": "Hey @AlexMV12 , we've released the patch that downgrades litellm. This should be fixed now!"
      }
    ]
  }
]