[
  {
    "number": 127,
    "title": "Setting batch_cfg=True produces slightly different results",
    "created_at": "2025-01-12T20:32:53Z",
    "closed_at": "2025-01-15T11:30:03Z",
    "labels": [],
    "url": "https://github.com/genmoai/mochi/issues/127",
    "body": "Hi, I was playing around with `batch_cfg` and am seeing different results when I enable/disable batching. Is this intended behaviour?\r\n\r\nCode to reproduce:\r\n```py\r\nimport numpy as np\r\nimport os\r\nfrom genmo.mochi_preview.pipelines import (\r\n    DecoderModelFactory,\r\n    DitModelFactory,\r\n    MochiPipeline,\r\n    T5ModelFactory,\r\n    linear_quadratic_schedule,\r\n)\r\n\r\nimport pickle\r\n\r\nMOCHI_DIR = \"./weights\"\r\n\r\npipeline = MochiPipeline(\r\n    text_encoder_factory=T5ModelFactory(),\r\n    dit_factory=DitModelFactory(\r\n        model_path=f\"{MOCHI_DIR}/dit.safetensors\", model_dtype=\"bf16\"\r\n    ),\r\n    decoder_factory=DecoderModelFactory(\r\n        model_path=f\"{MOCHI_DIR}/decoder.safetensors\",\r\n    ),\r\n    decode_type=\"tiled_full\",\r\n    cpu_offload=True\r\n)\r\n\r\ncfgs = [\r\n    (dict(\r\n        height=480,\r\n        width=848,\r\n        num_frames=31,\r\n        num_inference_steps=64,\r\n        sigma_schedule=linear_quadratic_schedule(64, 0.025),\r\n        cfg_schedule=[4.5] * 64,\r\n        batch_cfg=False,\r\n        prompt=\"A spinning globe on a wooden desk.\",\r\n        negative_prompt=\"\",\r\n        seed=12345,\r\n    ), \"ref_unbatched.pkl\"),\r\n    (dict(\r\n        height=480,\r\n        width=848,\r\n        num_frames=31,\r\n        num_inference_steps=64,\r\n        sigma_schedule=linear_quadratic_schedule(64, 0.025),\r\n        cfg_schedule=[4.5] * 64,\r\n        batch_cfg=True,\r\n        prompt=\"A spinning globe on a wooden desk.\",\r\n        negative_prompt=\"\",\r\n        seed=12345,\r\n    ), \"ref_batched.pkl\")\r\n]\r\n\r\nvideos = []\r\nfor cfg, fname in cfgs:\r\n    video = pipeline(**cfg)\r\n    videos.append(video)\r\n        \r\nprint(np.allclose(videos[0], videos[1]))\r\n```\r\n\r\nNote: The generated videos look roughly the same",
    "comments_url": "https://api.github.com/repos/genmoai/mochi/issues/127/comments",
    "author": "Akshat-Tripathi",
    "comments": [
      {
        "user": "ajayjain",
        "created_at": "2025-01-14T23:47:24Z",
        "body": "Hi @Akshat-Tripathi,\r\n\r\nDo you have any visual examples comparing the two videos?\r\n\r\nSome slight numerical differences are expected between batch_cfg=False and batch_cfg=True due to CUDA kernel differences in the framework.\r\n\r\nIf there's a significant difference in the videos, we'd be happy to check for a bug."
      },
      {
        "user": "Akshat-Tripathi",
        "created_at": "2025-01-15T11:30:04Z",
        "body": "Hi @ajayjain,\r\n\r\nYeah I've got a few videos generated without any noticeable differences. Kernel differences does make sense as a reason thanks!"
      }
    ]
  },
  {
    "number": 117,
    "title": "Web monthly credits is not resetting.",
    "created_at": "2024-12-16T13:24:14Z",
    "closed_at": "2024-12-16T18:32:05Z",
    "labels": [],
    "url": "https://github.com/genmoai/mochi/issues/117",
    "body": "### So here's the full story.\r\n\r\nFirst of all, I ran out of my monthly credits in the free plan. And It just keeps saying a date over today's date saying the credits will reset in that day but it just keeps getting over and over again. For example:\r\n\r\nIf it says **The credits will reset in 16 Dec** , then when 16 Dec comes, it will say **The credits will reset in 17 Dec** and so on.\r\nI waited over a month to see if it will go away but it does not. I hope this gets fixed. I don't know if this is just an issue on my part but can someone please help me?\r\n\r\nThank you.\r\n-Creppy",
    "comments_url": "https://api.github.com/repos/genmoai/mochi/issues/117/comments",
    "author": "CreppyMC",
    "comments": [
      {
        "user": "akbar-genmo",
        "created_at": "2024-12-16T18:32:05Z",
        "body": "Hi, thanks for bringing up this issue, I've shared the details with our product team. We will follow up on our discord which is the right channel for this kind of stuff :) "
      },
      {
        "user": "sidd-genmo",
        "created_at": "2024-12-16T19:31:00Z",
        "body": "Hey @CreppyMC, I work on product at Genmo. Thank you for flagging this issueâ€“we've pushed out a fix that should be ready  soon. \r\n\r\nIn the meantime, do you mind sending me your genmo username? I'd like to grant you extra generation credits for bringing this up. If you have discord, we can continue the conversation there ðŸ˜„ "
      }
    ]
  },
  {
    "number": 93,
    "title": "TypeError: configure_model() missing 1 required positional argument: 'cpu_offload_'",
    "created_at": "2024-11-28T16:18:48Z",
    "closed_at": "2024-11-30T09:43:00Z",
    "labels": [],
    "url": "https://github.com/genmoai/mochi/issues/93",
    "body": "TypeError: configure_model() missing 1 required positional argument: 'cpu_offload_'\r\nstart gradio\r\nI will encounter this problem regardless of whether I pass this parameter or not\r\nHere are some startup parameters I have tried\r\npython3 ./demos/gradio_ui.py --model_dir weights/ --cpu_offload true\r\npython3 ./demos/gradio_ui.py --model_dir weights/ --cpu_offload false\r\npython3 ./demos/gradio_ui.py --model_dir weights/ ",
    "comments_url": "https://api.github.com/repos/genmoai/mochi/issues/93/comments",
    "author": "ysxk",
    "comments": [
      {
        "user": "paras-genmo",
        "created_at": "2024-11-30T09:40:06Z",
        "body": "Hi @ysxk, this is a bug introduced by our LoRA trainer. I'm working on a fix which should be out soon. In the meantime, `./demos/cli.py` works. Thanks for reporting!"
      },
      {
        "user": "paras-genmo",
        "created_at": "2024-11-30T09:43:53Z",
        "body": "@ysxk gradio_ui.py is now fixed. You can use it with:\r\n```\r\npython3 ./demos/gradio_ui.py --model_dir weights/ --cpu_offload\r\n```\r\nor\r\n```\r\npython3 ./demos/gradio_ui.py --model_dir weights/\r\n```\r\n"
      },
      {
        "user": "ysxk",
        "created_at": "2024-12-01T06:07:21Z",
        "body": "thanks"
      }
    ]
  },
  {
    "number": 87,
    "title": "Add gdown pip package",
    "created_at": "2024-11-27T00:36:30Z",
    "closed_at": "2024-11-29T07:15:49Z",
    "labels": [],
    "url": "https://github.com/genmoai/mochi/pull/87",
    "body": null,
    "comments_url": "https://api.github.com/repos/genmoai/mochi/issues/87/comments",
    "author": "Wesxdz",
    "comments": [
      {
        "user": "erik-dunteman",
        "created_at": "2024-11-27T03:52:41Z",
        "body": "Good catch! Thanks for adding.\r\n\r\n@ajayjain confirming that this PR is helpful."
      }
    ]
  },
  {
    "number": 76,
    "title": "Add path for t5 model",
    "created_at": "2024-11-11T16:34:39Z",
    "closed_at": "2024-11-15T02:30:04Z",
    "labels": [],
    "url": "https://github.com/genmoai/mochi/pull/76",
    "body": "Hey :)\r\nThank you for your work! I added path to t5 model, because do not want to load one more T5 if I have one :)\r\n\r\nExample using:\r\n```python\r\nMOCHI_DIR =  \"/workspace/hf_cache/mochi\"\r\nT5_DIR = \"/workspace/hf_cache/t5-v1_1-xxl\"\r\n\r\npipeline = MochiSingleGPUPipeline(\r\n    text_encoder_factory=T5ModelFactory(\r\n        model_dir=T5_DIR\r\n    ),\r\n    dit_factory=DitModelFactory(\r\n        model_path=f\"{MOCHI_DIR}/dit.safetensors\", \r\n        model_dtype=\"bf16\"\r\n    ),\r\n    decoder_factory=DecoderModelFactory(\r\n        model_path=f\"{MOCHI_DIR}/decoder.safetensors\",\r\n    ),\r\n    cpu_offload=True,\r\n    decode_type=\"tiled_full\"\r\n)\r\n```\r\nor just as your example in readme.\r\n\r\nTested on A100",
    "comments_url": "https://api.github.com/repos/genmoai/mochi/issues/76/comments",
    "author": "TheDenk",
    "comments": [
      {
        "user": "ved-genmo",
        "created_at": "2024-11-15T02:30:01Z",
        "body": "Very useful, thanks!"
      }
    ]
  },
  {
    "number": 75,
    "title": "add mochi-xdit in readme",
    "created_at": "2024-11-11T03:04:52Z",
    "closed_at": "2024-11-13T21:00:55Z",
    "labels": [],
    "url": "https://github.com/genmoai/mochi/pull/75",
    "body": "@ajayjain Hello, this is an MR from the xDiT team. We have put som effort into optimizing the parallel inference speedup of mochi-1. I wish you could add our friendly-link in your readme.\r\n",
    "comments_url": "https://api.github.com/repos/genmoai/mochi/issues/75/comments",
    "author": "feifeibear",
    "comments": [
      {
        "user": "ved-genmo",
        "created_at": "2024-11-13T21:00:51Z",
        "body": "Amazing work! Thank you."
      }
    ]
  },
  {
    "number": 73,
    "title": "Update README.md",
    "created_at": "2024-11-10T00:33:18Z",
    "closed_at": "2024-11-17T03:48:34Z",
    "labels": [],
    "url": "https://github.com/genmoai/mochi/pull/73",
    "body": "added video tutorial link",
    "comments_url": "https://api.github.com/repos/genmoai/mochi/issues/73/comments",
    "author": "FurkanGozukara",
    "comments": [
      {
        "user": "ajayjain",
        "created_at": "2024-11-17T03:48:34Z",
        "body": "@FurkanGozukara Thanks for sharing a tutorial with the community. We're not linking tutorials from the README at the moment, but may do so in the future."
      }
    ]
  },
  {
    "number": 67,
    "title": " VAE Fourier feature",
    "created_at": "2024-11-06T06:32:38Z",
    "closed_at": "2024-11-17T03:39:17Z",
    "labels": [],
    "url": "https://github.com/genmoai/mochi/issues/67",
    "body": "Good job!\r\nWe found that the settings in vae are start=6, stop=8 to get w = torch.pow(2.0, freqs) * (2 * torch.pi) , what is the special meaning of this frequency? When we train vae, do we add frequency domain features to the video before feeding it into the model?",
    "comments_url": "https://api.github.com/repos/genmoai/mochi/issues/67/comments",
    "author": "GooThinker",
    "comments": [
      {
        "user": "ved-genmo",
        "created_at": "2024-11-13T20:59:04Z",
        "body": "Checkout `test_encoder_decoder.py` to see how to use the fourier features. @ajayjain what's the reasoning behind these constants?"
      },
      {
        "user": "ajayjain",
        "created_at": "2024-11-17T03:32:30Z",
        "body": "The VAE is trained with those constants, so you should keep using those specific values. It's also important to compute those features in float32, not quantized.\r\n\r\nThe fourier features help the encoder see fine-grained differences in pixel values. For example, a neural network might struggle to differentiate a pixel with color 254 versus 255, and the frequencies provided by the fourier features make the difference more obvious."
      }
    ]
  },
  {
    "number": 55,
    "title": "cannot import name 'decoded_latents_to_frames' from 'genmo.mochi_preview.vae.models'",
    "created_at": "2024-11-01T05:41:52Z",
    "closed_at": "2024-11-01T19:01:46Z",
    "labels": [],
    "url": "https://github.com/genmoai/mochi/issues/55",
    "body": "There is no decoded_latents_to_frames method in genmo.mochi_preview.vae.models",
    "comments_url": "https://api.github.com/repos/genmoai/mochi/issues/55/comments",
    "author": "v4if",
    "comments": [
      {
        "user": "ved-genmo",
        "created_at": "2024-11-01T19:01:46Z",
        "body": "@v4if This bug has been fixed, `git pull` and try again?"
      }
    ]
  },
  {
    "number": 49,
    "title": "MochiSingleGPUPipeline.__init__() got an unexpected keyword argument 'tiled_decode'",
    "created_at": "2024-10-31T21:39:25Z",
    "closed_at": "2024-11-01T03:24:32Z",
    "labels": [],
    "url": "https://github.com/genmoai/mochi/issues/49",
    "body": "I get this error when I try to generate a video:\r\n\r\n```\r\nTraceback (most recent call last):\r\n  File \"/home/kaki/Documents/models/.venv/lib/python3.10/site-packages/gradio/queueing.py\", line 624, in process_events\r\n    response = await route_utils.call_process_api(\r\n  File \"/home/kaki/Documents/models/.venv/lib/python3.10/site-packages/gradio/route_utils.py\", line 323, in call_process_api\r\n    output = await app.get_blocks().process_api(\r\n  File \"/home/kaki/Documents/models/.venv/lib/python3.10/site-packages/gradio/blocks.py\", line 2018, in process_api\r\n    result = await self.call_function(\r\n  File \"/home/kaki/Documents/models/.venv/lib/python3.10/site-packages/gradio/blocks.py\", line 1567, in call_function\r\n    prediction = await anyio.to_thread.run_sync(  # type: ignore\r\n  File \"/home/kaki/Documents/models/.venv/lib/python3.10/site-packages/anyio/to_thread.py\", line 56, in run_sync\r\n    return await get_async_backend().run_sync_in_worker_thread(\r\n  File \"/home/kaki/Documents/models/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py\", line 2441, in run_sync_in_worker_thread\r\n    return await future\r\n  File \"/home/kaki/Documents/models/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py\", line 943, in run\r\n    result = context.run(func, *args)\r\n  File \"/home/kaki/Documents/models/.venv/lib/python3.10/site-packages/gradio/utils.py\", line 846, in wrapper\r\n    response = f(*args, **kwargs)\r\n  File \"/home/kaki/Documents/models/demos/cli.py\", line 66, in generate_video\r\n    load_model()\r\n  File \"/home/kaki/Documents/models/demos/cli.py\", line 53, in load_model\r\n    pipeline = klass(**kwargs)\r\nTypeError: MochiSingleGPUPipeline.__init__() got an unexpected keyword argument 'tiled_decode'\r\n```\r\n\r\nWhat should I do?",
    "comments_url": "https://api.github.com/repos/genmoai/mochi/issues/49/comments",
    "author": "Kaki-In",
    "comments": [
      {
        "user": "ved-genmo",
        "created_at": "2024-11-01T03:24:32Z",
        "body": "should be fixed now"
      },
      {
        "user": "Kaki-In",
        "created_at": "2024-11-01T09:18:12Z",
        "body": "It seems really slow, even if I have a nvidia GPU. Did I miss something?"
      }
    ]
  },
  {
    "number": 48,
    "title": "    assert x == y, f\"{msg or 'Assertion failed'}: {x} != {y}\" AssertionError: t - 1 must be divisible by 6: 3 != 0",
    "created_at": "2024-10-31T15:40:49Z",
    "closed_at": "2024-11-06T21:10:43Z",
    "labels": [],
    "url": "https://github.com/genmoai/mochi/issues/48",
    "body": "all the time I get     assert x == y, f\"{msg or 'Assertion failed'}: {x} != {y}\"\r\nAssertionError: t - 1 must be divisible by 6: 3 != 0",
    "comments_url": "https://api.github.com/repos/genmoai/mochi/issues/48/comments",
    "author": "Sequential-circuits",
    "comments": [
      {
        "user": "akbar-genmo",
        "created_at": "2024-11-06T21:10:43Z",
        "body": "Hey, please see #37."
      }
    ]
  },
  {
    "number": 47,
    "title": "Can it be used for image to video generation?",
    "created_at": "2024-10-31T11:54:31Z",
    "closed_at": "2024-10-31T20:47:05Z",
    "labels": [],
    "url": "https://github.com/genmoai/mochi/issues/47",
    "body": "Can it be used for image to video generation?",
    "comments_url": "https://api.github.com/repos/genmoai/mochi/issues/47/comments",
    "author": "rajatanand86",
    "comments": [
      {
        "user": "yan-genmo",
        "created_at": "2024-10-31T20:47:05Z",
        "body": "Hi @rajatanand86, the current repo doesn't support image-to-video. We're working on image-to-video capabilities."
      }
    ]
  },
  {
    "number": 43,
    "title": "For all who has No module named 'mochi_preview'",
    "created_at": "2024-10-30T18:29:08Z",
    "closed_at": "2025-01-08T21:15:56Z",
    "labels": [],
    "url": "https://github.com/genmoai/mochi/issues/43",
    "body": "run \r\n\r\ngit pull \r\n\r\nto update\r\n\r\nthen go to \"demos\" folder and move all files to the \"src\" folder\r\n\r\nrun them from \"src\" folder\r\n\r\n\r\n\r\n\r\n\r\n\r\n",
    "comments_url": "https://api.github.com/repos/genmoai/mochi/issues/43/comments",
    "author": "ptits",
    "comments": [
      {
        "user": "ved-genmo",
        "created_at": "2024-11-01T03:14:40Z",
        "body": "Thank you for the guide -- I believe you can also do:\r\n```\r\nuv pip install -e . --no-build-isolation\r\n```\r\nto re-install the package (we moved stuff to the `genmo` namespace)"
      },
      {
        "user": "bbecausereasonss",
        "created_at": "2024-11-01T14:07:11Z",
        "body": "No luck. This build/structure is very confusing.\r\n\r\nAlso calling the repo folder /models was a mistake."
      },
      {
        "user": "bbecausereasonss",
        "created_at": "2024-11-01T16:18:04Z",
        "body": "What do you mean run them from src folder, and why woud you have to do this?"
      },
      {
        "user": "ved-genmo",
        "created_at": "2024-11-01T19:01:31Z",
        "body": "@bbecausereasonss You shouldn't need to do this. Just `git pull` and then rerun the `pip install` command (likely `uv pip install -e . --no-build-isolation`), this will re-install the package."
      },
      {
        "user": "bbecausereasonss",
        "created_at": "2024-11-01T23:32:43Z",
        "body": "Okay, for some reason it worked but now Im getting Torch not compiled for Cuda. These install instructions suck :/"
      },
      {
        "user": "bbecausereasonss",
        "created_at": "2024-11-01T23:39:11Z",
        "body": "Successfully installed torch-2.5.1+cu124 torchaudio-2.5.1+cu124\r\n\r\nAssertionError: Torch not compiled with CUDA enabled"
      },
      {
        "user": "ved-genmo",
        "created_at": "2025-01-08T21:16:23Z",
        "body": "@bbecausereasonss Let me know if this is still an issue for you."
      }
    ]
  },
  {
    "number": 39,
    "title": "nested progress bars in cli.py",
    "created_at": "2024-10-29T23:27:26Z",
    "closed_at": "2024-11-01T03:22:57Z",
    "labels": [],
    "url": "https://github.com/genmoai/mochi/issues/39",
    "body": "    with progress_bar(type=\"tqdm\"):\r\n        final_frames = pipeline(**args)\r\n        ...\r\n\r\nFOR SINGLE GPU:\r\n\r\nTiming load_text_encoder\r\nTiming load_dit\r\nTiming load_vae\r\nStage                   Time(s)    Percent\r\nload_text_encoder          5.93      2.87%\r\nload_dit                 193.06     93.39%\r\nload_vae                   7.73      3.74%\r\nTraceback (most recent call last):\r\n  File \"/home/jovyan/models/cli.py\", line 152, in <module>\r\n    generate_cli()\r\n  File \"/opt/conda/lib/python3.11/site-packages/click/core.py\", line 1157, in __call__\r\n    return self.main(*args, **kwargs)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"/opt/conda/lib/python3.11/site-packages/click/core.py\", line 1078, in main\r\n    rv = self.invoke(ctx)\r\n         ^^^^^^^^^^^^^^^^\r\n  File \"/opt/conda/lib/python3.11/site-packages/click/core.py\", line 1434, in invoke\r\n    return ctx.invoke(self.callback, **ctx.params)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"/opt/conda/lib/python3.11/site-packages/click/core.py\", line 783, in invoke\r\n    return __callback(*args, **kwargs)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"/home/jovyan/models/cli.py\", line 138, in generate_cli\r\n    output = generate_video(\r\n             ^^^^^^^^^^^^^^^\r\n  File \"/home/jovyan/models/cli.py\", line 94, in generate_video\r\n    final_frames = pipeline(**args)\r\n                   ^^^^^^^^^^^^^^^^\r\n  File \"/home/jovyan/models/genmo/mochi_preview/pipelines.py\", line 536, in __call__\r\n    with progress_bar(type=\"tqdm\"), torch.inference_mode():\r\n  File \"/opt/conda/lib/python3.11/contextlib.py\", line 137, in __enter__\r\n    return next(self.gen)\r\n           ^^^^^^^^^^^^^^\r\n  File \"/home/jovyan/models/genmo/lib/progress.py\", line 78, in progress_bar\r\n    raise RuntimeError(\"Nested progress bars are not supported\")\r\nRuntimeError: Nested progress bars are not supported",
    "comments_url": "https://api.github.com/repos/genmoai/mochi/issues/39/comments",
    "author": "ptits",
    "comments": [
      {
        "user": "ved-genmo",
        "created_at": "2024-11-01T03:22:57Z",
        "body": "should be fixed now"
      }
    ]
  },
  {
    "number": 35,
    "title": "No module named 'genmo'",
    "created_at": "2024-10-29T15:15:03Z",
    "closed_at": "2024-12-20T23:11:31Z",
    "labels": [],
    "url": "https://github.com/genmoai/mochi/issues/35",
    "body": "(.venv) D:\\PyShit\\genmo-test\\models>python3 ./demos/gradio_ui.py --model_dir \"D:\\PyShit\\genmo-test\\genmoModels\"\r\n\r\nTraceback (most recent call last):\r\n  File \"D:\\PyShit\\genmo-test\\models\\demos\\gradio_ui.py\", line 9, in <module>\r\n    from cli import generate_video, configure_model\r\n  File \"D:\\PyShit\\genmo-test\\models\\demos\\cli.py\", line 10, in <module>\r\n    from genmo.mochi_preview.pipelines import (\r\nModuleNotFoundError: No module named 'genmo'",
    "comments_url": "https://api.github.com/repos/genmoai/mochi/issues/35/comments",
    "author": "MinervaArgus",
    "comments": [
      {
        "user": "ptits",
        "created_at": "2024-10-29T18:34:01Z",
        "body": "copy all py files from demos to root (models) folder\r\nthere is a mess with folders and paths (src\\..)\r\n"
      },
      {
        "user": "MinervaArgus",
        "created_at": "2024-10-30T00:05:48Z",
        "body": "> copy all py files from demos to root (models) folder there is a mess with folders and paths (src..)\r\n\r\nstill gives me the same error, i also tried 'python3 gradio_ui.py --model_dir \"D:\\PyShit\\genmo-test\\genmoModels\"' and that did not work either"
      },
      {
        "user": "Sequential-circuits",
        "created_at": "2024-10-30T12:13:40Z",
        "body": "same error here"
      },
      {
        "user": "arcinin1",
        "created_at": "2024-11-02T19:34:22Z",
        "body": "currently having problem with \"genmo.lib\".\r\n\r\nTraceback (most recent call last):\r\n  File \"C:\\Users\\Wspolny\\Desktop\\models\\demos\\gradio_ui.py\", line 10, in <module>\r\n    from cli import configure_model, generate_video\r\n  File \"C:\\Users\\Wspolny\\Desktop\\models\\demos\\cli.py\", line 10, in <module>\r\n    from genmo.lib.progress import progress_bar\r\nModuleNotFoundError: No module named 'genmo.lib'"
      },
      {
        "user": "piradata",
        "created_at": "2024-11-04T04:09:02Z",
        "body": "same problem here, someone got it solved?"
      },
      {
        "user": "piradata",
        "created_at": "2024-11-04T04:30:39Z",
        "body": "ok, fixed it"
      },
      {
        "user": "arcinin1",
        "created_at": "2024-11-04T07:48:26Z",
        "body": "> ok, fixed it\r\n\r\nHow did you fix it?"
      },
      {
        "user": "khydrogenous",
        "created_at": "2024-11-05T10:54:47Z",
        "body": "Any updates on solving genmo.lib?\r\n"
      },
      {
        "user": "piradata",
        "created_at": "2024-11-05T16:39:52Z",
        "body": "> > ok, fixed it\n> \n> How did you fix it?\n\ni did open a pr with the fix, but basically, it happens because either the path is not added correctly (adding .. to path is dependent on the directory you are curently in) and because even if the path is added the lib should be referenced as src.genmo"
      },
      {
        "user": "khydrogenous",
        "created_at": "2024-11-06T02:59:41Z",
        "body": "Thanks, I just solved it too after I realized that \"your-dir\" from python3 ./demos/cli.py --model_dir your-dir has to be the full path, it cannot include any wildcards or placeholders. Perhaps a Readme clarification would help?"
      },
      {
        "user": "bsab",
        "created_at": "2024-11-11T15:05:28Z",
        "body": "To resolve the issue, please copy the __init__.py file to both the genmo directory and the genmo/lib directory. \r\nAdditionally, make sure to move the demo/cli.py file under the src directory. This should help in fixing the problem."
      },
      {
        "user": "lavaraja",
        "created_at": "2024-11-12T00:14:48Z",
        "body": "after cloning the repo run `pip install -ve .` inside `models` folder to fix `No module named 'genmo'` issue. "
      }
    ]
  },
  {
    "number": 27,
    "title": "Is flash-attn still necessary?",
    "created_at": "2024-10-25T19:39:52Z",
    "closed_at": "2024-10-28T22:20:13Z",
    "labels": [],
    "url": "https://github.com/genmoai/mochi/issues/27",
    "body": "Using the latest depo I encounter the error:\r\n```\r\n  File \"D:\\PythonProjects\\genmoai-smol\\src\\mochi_preview\\dit\\joint_model\\asymm_models_joint.py\", line 8, in <module>\r\n    from flash_attn import flash_attn_varlen_qkvpacked_func\r\nModuleNotFoundError: No module named 'flash_attn'\r\n```\r\nIf I install` flash-attn` wheels (Windows, Python 3.10) from author's HuggingFace and run inference I see\r\n```\r\n    import flash_attn_2_cuda as flash_attn_cuda\r\nImportError: DLL load failed while importing flash_attn_2_cuda: The specified procedure could not be found\r\n```\r\n",
    "comments_url": "https://api.github.com/repos/genmoai/mochi/issues/27/comments",
    "author": "SuperMaximus1984",
    "comments": [
      {
        "user": "ved-genmo",
        "created_at": "2024-10-28T22:20:13Z",
        "body": "Not anymore! Pull the latest release and follow the instructions in the README."
      }
    ]
  },
  {
    "number": 23,
    "title": "Only .json in ./outputs",
    "created_at": "2024-10-24T12:13:21Z",
    "closed_at": "2024-10-28T22:23:10Z",
    "labels": [],
    "url": "https://github.com/genmoai/mochi/issues/23",
    "body": "After I run the program, whether using the Gradio UI or CLI, when the tqdm progress bar completes, there are only .json files in the outputs folder, and no .mp4 files",
    "comments_url": "https://api.github.com/repos/genmoai/mochi/issues/23/comments",
    "author": "Xiuzhenpeng",
    "comments": [
      {
        "user": "kaixin96",
        "created_at": "2024-10-28T11:21:48Z",
        "body": "`ffmpeg` is missing in the requirement. It's needed to generate the mp4 file."
      },
      {
        "user": "ved-genmo",
        "created_at": "2024-10-28T22:23:10Z",
        "body": "Added instructions to README."
      }
    ]
  },
  {
    "number": 20,
    "title": "No module named 'click'",
    "created_at": "2024-10-24T06:35:52Z",
    "closed_at": "2024-10-29T18:26:12Z",
    "labels": [],
    "url": "https://github.com/genmoai/mochi/issues/20",
    "body": "i keep pip installing this --force --upgrade even tried with conda.. hmm.. any ideas?",
    "comments_url": "https://api.github.com/repos/genmoai/mochi/issues/20/comments",
    "author": "gjnave",
    "comments": [
      {
        "user": "yan-genmo",
        "created_at": "2024-10-28T22:37:39Z",
        "body": "Hi gjnave, did you use `uv pip install click` instead of `pip install click`, if you're using uv as we suggested?\r\nIf not, can you show us the exact command you used and the error message?"
      },
      {
        "user": "Shenyi-Z",
        "created_at": "2024-10-29T11:20:44Z",
        "body": "Hi, I encountered a similar issue while trying to deploy the model. As @yan-genmo mentioned, using uv can avoid this problem, or you can create a conda environment in a similar way to circumvent the issue."
      },
      {
        "user": "gjnave",
        "created_at": "2024-10-29T18:23:02Z",
        "body": "Thank you all for the responses. I believe I did use the UV but perhaps I missed something. Or while I wa s reinstalling click was using pip instead of UV\r\n\r\nMy biggest snag with this project was that I realized you need 4h100s :) I was able to find a q8 version and run this on 24 GB and did make impressive videos. I'm really looking forward to see what you are doing in the future.\r\n\r\nMy warm regards to you and you can consider this issue closed. Thank you once again"
      },
      {
        "user": "yan-genmo",
        "created_at": "2024-10-29T18:26:12Z",
        "body": "Thank you! Please let us know if you have more questions. I will close this issue."
      }
    ]
  },
  {
    "number": 18,
    "title": "does this project have a pre-built Docker image?",
    "created_at": "2024-10-24T02:08:10Z",
    "closed_at": "2024-12-20T23:08:26Z",
    "labels": [],
    "url": "https://github.com/genmoai/mochi/issues/18",
    "body": null,
    "comments_url": "https://api.github.com/repos/genmoai/mochi/issues/18/comments",
    "author": "yeyeyeyeeeee",
    "comments": [
      {
        "user": "ved-genmo",
        "created_at": "2024-12-20T23:08:26Z",
        "body": "not yet"
      }
    ]
  },
  {
    "number": 15,
    "title": "Will training/finetuning codes be released?",
    "created_at": "2024-10-23T17:32:38Z",
    "closed_at": "2024-10-23T21:30:24Z",
    "labels": [],
    "url": "https://github.com/genmoai/mochi/issues/15",
    "body": "Thank you for your great work! Will the training/finetuning codes also be released?",
    "comments_url": "https://api.github.com/repos/genmoai/mochi/issues/15/comments",
    "author": "wang-sj16",
    "comments": [
      {
        "user": "akbar-genmo",
        "created_at": "2024-10-23T21:30:24Z",
        "body": "Thanks for your interest. See #1 please. "
      }
    ]
  },
  {
    "number": 13,
    "title": "text encoders",
    "created_at": "2024-10-23T10:53:38Z",
    "closed_at": "2024-10-23T14:32:55Z",
    "labels": [],
    "url": "https://github.com/genmoai/mochi/issues/13",
    "body": "I dont see any code (inside this branch\\fork) which download and store T5 model and encoders\r\n\r\nMay be i am dumb but please show me where (in which .py file) hf_hub_download or wget are used\r\n\r\nI see T5_MODEL = \"google/t5-v1_1-xxl\"  and dont see how it is dowloaded with code\r\n\r\n",
    "comments_url": "https://api.github.com/repos/genmoai/mochi/issues/13/comments",
    "author": "ptits",
    "comments": [
      {
        "user": "Cascade42",
        "created_at": "2024-10-23T13:48:23Z",
        "body": "Just follow the chain of function calls.\r\nThe model is downloaded by T5Tokenizer.from_pretrained() / T5EncoderModel.from_pretrained() from the transformers library, which will then eventually download the model using the huggingface_hub library.\r\nCheck your site-packages if you want to see the code."
      }
    ]
  },
  {
    "number": 9,
    "title": "vae encoder is missing? ",
    "created_at": "2024-10-22T23:37:39Z",
    "closed_at": "2024-10-23T00:59:07Z",
    "labels": [],
    "url": "https://github.com/genmoai/mochi/issues/9",
    "body": "Will the vae encoder be released so that we have the full model for vae? ",
    "comments_url": "https://api.github.com/repos/genmoai/mochi/issues/9/comments",
    "author": "aaxwaz",
    "comments": [
      {
        "user": "ved-genmo",
        "created_at": "2024-10-23T00:59:05Z",
        "body": "We will be open-sourcing the encoder, stay tuned :)"
      }
    ]
  },
  {
    "number": 8,
    "title": "Will it work on 4xA100? 80gb VRAM each",
    "created_at": "2024-10-22T23:36:56Z",
    "closed_at": "2024-10-22T23:40:57Z",
    "labels": [],
    "url": "https://github.com/genmoai/mochi/issues/8",
    "body": null,
    "comments_url": "https://api.github.com/repos/genmoai/mochi/issues/8/comments",
    "author": "ptits",
    "comments": [
      {
        "user": "ved-genmo",
        "created_at": "2024-10-22T23:40:57Z",
        "body": "It should, yes."
      }
    ]
  },
  {
    "number": 5,
    "title": "cfg-scale should be cfg_scale",
    "created_at": "2024-10-22T21:33:58Z",
    "closed_at": "2024-10-22T21:51:29Z",
    "labels": [],
    "url": "https://github.com/genmoai/mochi/pull/5",
    "body": null,
    "comments_url": "https://api.github.com/repos/genmoai/mochi/issues/5/comments",
    "author": "tovacinni",
    "comments": [
      {
        "user": "yan-genmo",
        "created_at": "2024-10-22T21:50:47Z",
        "body": "Thanks for the correction!"
      }
    ]
  },
  {
    "number": 4,
    "title": "TypeError: AsymmetricAttention.__init__() got an unexpected keyword argument 'clip_feat_dim'",
    "created_at": "2024-10-22T21:29:25Z",
    "closed_at": "2024-10-22T23:41:42Z",
    "labels": [],
    "url": "https://github.com/genmoai/mochi/issues/4",
    "body": null,
    "comments_url": "https://api.github.com/repos/genmoai/mochi/issues/4/comments",
    "author": "cene555",
    "comments": [
      {
        "user": "ved-genmo",
        "created_at": "2024-10-22T22:45:17Z",
        "body": "Hi! Thanks for trying out the inference repo. Can you provide the dit-config.yaml you used to run the model?"
      },
      {
        "user": "rlsu9",
        "created_at": "2024-10-22T22:47:42Z",
        "body": "Hi, you can simple fix the error by deleting the unexpected keyworks from the dit-config.yaml. For me, I have deleted the `clip_feat_dim`, `pooled_caption_mlp_bias` and `use_transformer_engine` from dit-config.yaml and everything works fine. I guess its a mismatch between the ckpt on huggingface and the codebase."
      },
      {
        "user": "ved-genmo",
        "created_at": "2024-10-22T23:22:55Z",
        "body": "If you pull the latest version of this repository, this error should be gone @cene555."
      }
    ]
  },
  {
    "number": 1,
    "title": "Great work! Will you release the training code?",
    "created_at": "2024-10-22T17:53:19Z",
    "closed_at": "2024-10-22T20:54:08Z",
    "labels": [],
    "url": "https://github.com/genmoai/mochi/issues/1",
    "body": null,
    "comments_url": "https://api.github.com/repos/genmoai/mochi/issues/1/comments",
    "author": "yachty66",
    "comments": [
      {
        "user": "ajayjain",
        "created_at": "2024-10-22T20:54:08Z",
        "body": "Hi Yachty,\r\n\r\nThis is an inference-focused library initially for simplicity. We released a full model definition including our causal VAE and context parallel inference so you could try to implement a tuning loop. It's a bit computationally intensive to pre-train at the moment."
      }
    ]
  }
]